name: Bug Report 🪲
description: Create a bug report to help us improve
title: '[Bug]: '
labels: ['Bug Report', 'Needs Triage']
body:
  - type: markdown
    attributes:
      value: |
        # Please follow these steps first:
  - type: markdown
    attributes:
      value: |
        ## Troubleshoot
        If the library is not behaving the way you expect, we'd ask you to look at the [documentation](https://cuaklabs.github.io/iocuak-docs/) and search the issue tracker for evidence supporting your expectation. Please make reasonable efforts to troubleshoot and rule out issues with your code, the configuration, or any 3rd party libraries you might be using.
  - type: markdown
    attributes:
      value: |
        ## Make a minimal reproduction
        To file the report, you will need to provide a minimal (but complete) example and simple/clear steps on how to reproduce the bug.

        The simpler you can make it, the more likely we are to successfully verify and fix the bug.
  - type: markdown
    attributes:
      value: |
        :bangbang: &nbsp; Bug reports without a minimal reproduction will be rejected. :bangbang:

        ---
  - type: input
    id: version
    attributes:
      label: Version
      description: |
        The version of library you are using.
        Is it the latest? Test and see if the bug has already been fixed.
      placeholder: ex. 0.3.0
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Please provide a minimal reproduction and describe accurately how we can reproduce/verify the bug.
      placeholder: |
        Example steps (replace with your own):
        1. Clone my repo at https://github.com/<myuser>/example
        2. yarn install
        3. yarn test
        4. You should see the error come up
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A description of what you expect to happen.
      placeholder: I expect to see X or Y
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Actual behavior
      description: A clear and concise description of the unexpected behavior.
      placeholder: A bug happened!
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Anything else that might be relevant
    validations:
      required: false
  - type: textarea
    id: envinfo
    attributes:
      label: Environment
      description: |
        Please paste the output of running `npx envinfo --system --binaries --npmPackages`.
        This will be automatically formatted as a code block, so no need for backticks.
      placeholder: |
        System:
          OS: Linux 5.10 Debian GNU/Linux 9 (stretch)
          CPU: (8) arm64
        Binaries:
          Node: 14.17.0 - /usr/local/bin/node
          Yarn: 1.22.5 - /usr/local/bin/yarn
          npm: 6.14.13 - /usr/local/bin/npm
        npmPackages:
          @cuaklabs/iocuak: 0.3.0 => 0.3.0
      render: Shell
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---

        ## Aknowledgements

        This issue template is highly inspired by the [jest](https://github.com/facebook/jest/blob/main/.github/ISSUE_TEMPLATE/bug.yml) one, so I would like to thank the jest team for providing it ❤️.
